[build]
  command = "NODE_ENV=production gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[context.production]
  environment = { GATSBY_API_URL="https://thegiwi-email.herokuapp.com/api/contact" }
